"""add fields

Revision ID: fba396417537
Revises: a4d485040738
Create Date: 2023-06-11 20:42:33.858415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba396417537'
down_revision = 'a4d485040738'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teachers_id', table_name='teachers')
    op.drop_table('teachers')
    op.drop_table('department')
    op.drop_index('ix_courses_id', table_name='courses')
    op.drop_table('courses')
    op.drop_table('student_course')
    op.drop_index('ix_students_id', table_name='students')
    op.drop_table('students')
    op.drop_table('course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name='course_department_id_fkey'),
    sa.PrimaryKeyConstraint('course_id', name='course_pkey')
    )
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('students_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('surname_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='students_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_students_id', 'students', ['id'], unique=False)
    op.create_table('student_course',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='student_course_course_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='student_course_student_id_fkey')
    )
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='courses_pkey')
    )
    op.create_index('ix_courses_id', 'courses', ['id'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('faculty_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dep_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='department_pkey')
    )
    op.create_table('teachers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('surname_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='teachers_pkey')
    )
    op.create_index('ix_teachers_id', 'teachers', ['id'], unique=False)
    # ### end Alembic commands ###
